[build]
  publish = "_site"
  command = "eleventy"

[[redirects]]
  from = "/home/"
  to = "/"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "_site"
  prettyURLs = true
  exclude = [
    'https://www.societypizzeria.com.au/404/',
    'https://www.societypizzeria.com.au/404.html',
    'https://www.societypizzeria.com.au/admin/',
  ]
